### PR TITLE
Upgrade Android SDK, remove MemorizingTrustManager

### PR DESCRIPTION
**Pull request by dbrgn**
- Upgrade Android SDK to 29
- Upgrade Gradle and build tools
- Remove MemorizingTrustManager (see #70)
- Switch to CircleCI

Replaces #66.

### CODE REVIEW

**Comment by dbrgn** [comment]
Hmm, seems that Travis is not enabled anymore?

**Comment by rorist** [comment]
Ah yes correct, I've just relinked it.

**Comment by dbrgn** [comment]
This will probably still fail due to the MemorizingTrustManager using a different SDK version. I'll open a seprate PR to discuss that.

**Comment by dbrgn** [comment]
Hm, there's also another problem with the CI setup. And unfortunately the TravisCI docs about Android seem terribly outdated. Testing Android in CI is still a pain. I have no idea which versions are available.

What do you think about CircleCI? Their setup is Docker based, that allows you to test CI runs locally. They also allow you to SSH into build containers, in order to debug build problems. Like Travis, it's free for open source. I already have a configuration for Android testing on CircleCI from another project.

If you would like to give it a try, you would need to log in at https://circleci.com/ and enable builds for this repository. Make sure to also enable "Build forked pull requests" in the advanced settings of the project.

**Comment by rorist** [comment]
Sure, you can add the circleci file, the repo should be enabled. I've also enabled the pipelines. I don't know much about circleci, but sounds good.

**Comment by dbrgn** [comment]
Hm, doesn't seem to trigger. Maybe because the PR was created before CircleCI was enabled? I'll test it in a separate PR.

**Comment by dbrgn** [comment]
Cool, CI now works :) So far without an emulator, but that can be added if/once we have UI tests.

**Comment by rnestler** [comment]
> Hm, doesn't seem to trigger. Maybe because the PR was created before CircleCI was enabled? I'll test it in a separate PR.

You need to push again after enabling CircleCI so it triggers a build.

**Comment by dbrgn** [comment]
> You need to push again after enabling CircleCI so it triggers a build.

I did :wink: I later removed the commit during the force push. The actual reason was [this](https://github.com/coredump-ch/MyHackerspace/pull/1#issuecomment-592520721).

**Pull request merged**
