### PR TITLE
Improve DE translations

### PR DESCRIPTION
**Pull request by cyroxx**
Improved the German translations, especially the space status texts.

### CODE REVIEW

**Comment by rnestler** [comment]
@rorist Ready to merge I guess?

**Comment by dbrgn** [comment]
@cyroxx I integrated these changes into #85. You're mentioned as co-author of that commit!

**Comment by dbrgn** [comment]
#85 was merged in the fork, so this can probably be closed.

**Comment by niccokunzmann** [comment]
@dbrgn where is this app maintained?

**Comment by dbrgn** [comment]
@niccokunzmann it's here: https://github.com/spaceapi-community/my-hackerspace

**Comment by cyroxx** [comment]
Closing this because the changes were incorporated in the fork by this commit: https://github.com/spaceapi-community/my-hackerspace/commit/99876b541111b877b0016f0115f603c7bb2e369c

**Pull request closed without merging**
